### PR TITLE
BRITECH262- restructure for consistency

### PR DESCRIPTION
**Pull request by pallenSL**
Auth.Web -> Auth for folder, project file, namespace (x1, oddly), output files, build files.

### CODE REVIEW

**Comment by jebbinSCL** [comment]
I'm not sure, but I think that the build/pipeline folder has been moved to the infrastructure repo and isn't needed? I'm not sure if removing it will require other changes, but it is no longer present in the sessions repo for example

**Comment by pallenSL** [comment]
Did you mean Comms?
Githooks is another inconsistency I now note.

**Comment by jebbinSCL** [comment]
Ah, I was looking at the api gateway, but yeah, same with comms. I think the git hooks can be taken out now, we are just leaving the Bristech item reference in the pull request name.

**Comment by jebbinSCL** [comment]
:shipit:

**Pull request merged**
