### PR TITLE
Make it work on Mono

### PR DESCRIPTION
**Pull request by pallenSL**
Installation of AesDataProtectionProvider must be done before - not by - IdSrv3.
HttpListener 2.<something> was the cookie expiration bug.

### CODE REVIEW

**Comment by jebbinSCL** [comment]
I think you might have a configuration issue with your git? I think the entire files keep getting marked as change due to automatic line ending changes by one of the tools you are using (probably either VS or monodevelop). Could you take a quick look at that? It makes it hard to see what the true changes are. If its not a quick solve, I'll mark this for merge for now, and we can solve it tomorrow.

**Comment by jebbinSCL** [comment]
:shipit: after attempt to deal with line endings configuration.

**Comment by pallenSL** [comment]
Switching between the two seems to be the cause.  I did try removing the terminators in vi but it didn't improve.  The two IDEs also fight over case.
> git diff -w helps, if you know how to make the website do that.

**Comment by jebbinSCL** [comment]
I found out  how to do that: https://github.com/BristechSRM/auth/pull/11/files?w=1
Add ?w=1 to the url

**Comment by pallenSL** [comment]
Cool!  Now you can see the other Monodevelop vs VisualStudio isms.  I'm not sure what we want to do about those...

**Comment by ianlovell** [comment]
:shipit:

**Pull request merged**
