### PR TITLE
Britech-273 Changing folder structure to match the other projects

### PR DESCRIPTION
**Pull request by dwybourn**

### CODE REVIEW

**Comment by lclarksl** [comment]
This doesn't run anymore. It builds successfully but I get this error when running ./run.sh:
Cannot open assembly 'Auth.Web.exe': No such file or directory.

**Comment by dwybourn** [comment]
Well spotted. I’ve updated the build.fsx file. This time I’ve checked that it builds and runs.

**Comment by lclarksl** [comment]
:shipit:

**Comment by jebbinSCL** [comment]
:shipit:

**Pull request merged**
