### PR TITLE
GoogleOAuth2 from a more recent master

### PR DESCRIPTION
**Pull request by pallenSL**

### CODE REVIEW

**Comment by ianlovell** [comment]
:shipit:

**Comment by jebbinSCL** [comment]
I think if you want to have the secrets in now, they need to be in app.config rather than the secrets.config. Because secrets.config has already been ignored, it was not pulled when I pulled the repo

**Comment by ianlovell** [comment]
secrets.config is in the commit, showing as diff

**Comment by jebbinSCL** [comment]
Ah, nevermind, for some reason I had pulled the commit before the secrets.config was added

**Comment by jebbinSCL** [comment]
:shipit:

**Pull request merged**
