### PR TITLE
Britech-273 Fixing packages location

### PR DESCRIPTION
**Pull request by dwybourn**

### CODE REVIEW

**Comment by jebbinSCL** [comment]
I think we might still have some trouble here. I think that Visual studio will still install packages to the location one level up from the code.

The real issue isn't the packages, but the differences between the folder stucture of this repo and the others. We need to pick one and go with that.

**Comment by jebbinSCL** [comment]
Actually, now that I think about it, won't this break the build when some develops locally with visual studio or mono develop?

**Comment by dwybourn** [comment]
I've tested this change on

**Comment by dwybourn** [comment]
I tested it with the build script and visual studio before committing.

**Comment by dwybourn** [comment]
All of the other projects refer to the package folder in the root directory of the project. This is the only one that didn’t, which is why the build failed.

**Comment by jebbinSCL** [comment]
Hmm, thing is that visual studio isn't actually restoring packages to the targeted location, its restoring it to the original location. Since the reference is called a hint path, I believe that since Visual studio can't find the packages in the correct location, it has a number of other locations it searches. I've tested this by turning off my automatic restore and deleting the packages in both locations. The build still works because its looking elsewhere. 

Its convenient that it does that, but it can lead to the rare problem down the road, so I think we want to make sure it is definitely using the packages that we point it to. 

If we aren't going to make the folder structure consistent for all the repositories, I think that there is a way to tell nuget where it should be restoring the packages to, so that the packages are in the correct location. Maybe take a look at that?

**Comment by dwybourn** [comment]
I see, maybe we should change auth then to match the other projects then. This project has the auth/Source/Auth.Web whereas other projects have comms/Comms. So this repo has an depth of folders. Would you be happy if this was changed to match the others, e.g. auth/Auth?

**Comment by jebbinSCL** [comment]
It was Ian that originally setup this project with the /Source. Maybe we should have a quick group discussion about the structure to decide? I'm good with either, I just prefer that everything is consistent. I guess having things at the top level matches the folder structure of the build and deploy docker images?

**Comment by dwybourn** [comment]
I’d be inclined to change auth to match the other projects as they are already working with concourse.

**Comment by jebbinSCL** [comment]
Yeah, I think that is easiest. Lets see what the others think.

**Comment by ianlovell** [comment]
@dwybourn fine with me, just need this running today

**Pull request closed without merging**
