### PR TITLE
BRITECH367 - API scope DisplayName and Description

### PR DESCRIPTION
**Pull request by pallenSL**
And some informative Log.Debug()s for anyone picking this up!

### CODE REVIEW

**Comment by jebbinSCL** [comment]
The only problem I have with these debug strings over strings without the function signatures with them is that anyone who makes a future function name change will need to remember to change the debug string. If they were just descriptive without the function name, then they would probably stay the same, event with function name changes. 

I guess there isn't really a way around this though...

**Comment by jebbinSCL** [comment]
:shipit:

**Comment by pallenSL** [comment]
I've never found a better way of logging this level stuff - if you try to log in English it doesn't help you navigate the code.  You just end up doing a Find in Files for what you hope is a static string...

**Comment by jebbinSCL** [comment]
Maybe creating a library is needed... Or we give ids to every function for searching in logs...

**Pull request merged**
